name: Terraform Apply
on: [workflow_dispatch]
jobs:
#  Terraform-Init:
#    runs-on: self-hosted
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v5
#      - name: Terraform init
#        run: |
#          terraform init -backend-config=env-dev/state.tfvars
#
#  Terraform-Plan:
#    runs-on: self-hosted
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v5
#      - name: Terraform init
#        run: |
#          terraform init -backend-config=env-dev/state.tfvars
  Terraform-Apply:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Terraform init
        run: |
          export PATH=/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin 
          terraform init -backend-config=env-dev/state.tfvars
          terraform plan -var-file=env-dev/main.tfvars -var vault_token=${vault_token} 2 | tail -n6 | head -n1 >> $GITHUB_STEP_SUMMARY
        env:
          vault_token: ${{ secrets.vault_token }}
      - name: simple notify
        if: ${{ always() }}
        run: echo "Terraform finished - Status ${{ job.status }} on ${{ github.ref_name }} by ${{ github.actor }}"
#  Helm-Install-Applications:
#    runs-on: self-hosted
#    needs: Terraform-Apply
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v5
#        with:
#          repository: manjudevopszone/roboshop-helm
#          Path: helm
#      - name: Helm install application
#        run: |
#          export PATH=/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
#          cd helm
#          make dev


